Updated Pkglists, modified conky config to include todo.sh todo list info

diff --git a/.SyncArchive/config/zshrc b/.SyncArchive/config/zshrc
--- a/.SyncArchive/config/zshrc
+++ b/.SyncArchive/config/zshrc
@@ -26,7 +26,7 @@ autoload -U colors
 colors
 
 #Prompt with plenty of colour, and accurate time.
-PROMPT='[ $fg[blue]%n $fg[yellow]%m$fg[red]%(?.. %?) $reset_color%~ ]
+PROMPT='[ $fg[blue]%n $fg[yellow]%m$fg[red]%(?.. %?) $fg[green]%~$reset_color ]
 ⇀  '
 
 #Aliases
@@ -47,25 +47,25 @@ export EDITOR="vim"
 #File Extraction
 ex()
 {
-	if [ -f $1 ] ; then
-		case $1 in
-			*.tar.bz2)	tar xjf $1	;;
-			*.tar.gz)	tar xzf $1	;;
-			*.bz2)		bunzip2 $1	;;
-			*.rar)		unrar x $1	;;
-			*.gz)		gunzip $1	;;
-			*.tar)		tar xf $1	;;
-			*.tbz2)		tar xjf $1	;;
-			*.tgz)		tar xzf $1	;;
-			*.zip)		unzip $1	;;
-			*.Z)		uncompress $1	;;
-			*.7z)		7z x $1		;;
-			*.rpm)		bsdtar xvf $1 ;;
-			*.deb)		bsdtar xvf $1 ;;
-			*)			echo "'$1' cannot be extracted"	;;
+	if [ -f "$1" ] ; then
+		case "$1" in
+			*.tar.bz2)	tar xjf "$1"	;;
+			*.tar.gz)	tar xzf "$1"	;;
+			*.bz2)		bunzip2 "$1"	;;
+			*.rar)		unrar x "$1"	;;
+			*.gz)		gunzip "$1"	;;
+			*.tar)		tar xf "$1"	;;
+			*.tbz2)		tar xjf "$1"	;;
+			*.tgz)		tar xzf "$1"	;;
+			*.zip)		unzip "$1"	;;
+			*.Z)		uncompress "$1"	;;
+			*.7z)		7z x "$1"		;;
+			*.rpm)		bsdtar xvf "$1" ;;
+			*.deb)		bsdtar xvf "$1" ;;
+			*)			bsdtar xff "$1" || echo "'$1' cannot be extracted"	;;
 		esac
 	else
-		echo "'$1' is not a valid file"
+		echo "'$1' is not a file"
 	fi
 }
 
@@ -76,7 +76,7 @@ go()
 	ls;
 }
 
-#Screenlock Pause
+#Xautolock Pause
 pause()
 {
 	xautolock -disable
@@ -92,11 +92,11 @@ bindkey '^[[B' down-line-or-search
 command_not_found_handler(){
 	local pkgs cmd="$1"
 	pkgs=(${(f)"$(pkgfile -bv -- "$cmd" 2>/dev/null)"})
-	printf "$fg[red] I'm sorry, $LOGNAME. I'm afraid I can't do that. \n"
+	printf "$fg[red]I'm sorry, $LOGNAME. I'm afraid I can't do that. \n"
 	if [[ -n "$pkgs" ]]; then
-		printf "$fg[yellow] %s \n" $pkgs[@]
+		printf "$fg[blue]The following packages provide $1:\n$fg[yellow]%s\n" $pkgs[@]
 		return 0
 	else;
-		printf "No packages provide $1 \n"
+		printf "$fg[green]No packages provide $1 \n"
 	fi
 }
